# =============================================
# PERFIL "oracle": Base de datos Oracle Cloud
# =============================================
# Recuerda reemplazar <NOMBRE_TNS>, <USUARIO> y <PASSWORD>
spring.datasource.url=jdbc:oracle:thin:@<NOMBRE_TNS>?TNS_ADMIN=./src/main/resources/wallet
spring.datasource.username=<USUARIO>
spring.datasource.password=<PASSWORD>
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# "update" creará la tabla la primera vez sin borrar datos existentes luego
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Deshabilitamos la carga de data.sql para no pisar datos en la nube
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never