# =============================================
# PERFIL ACTIVO
# (Cambia a "oracle" cuando quieras probar con la nube)
# =============================================
spring.profiles.active=local

# =============================================
# CONFIGURACIÓN GENERAL (Puerto y Monitoreo)
# =============================================
server.port=8080
management.endpoints.web.exposure.include=health,info

# =============================================
# CONFIGURACIÓN RABBITMQ (Semana 7)
# =============================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# =============================================
# CONFIGURACIÓN AWS S3
# =============================================
aws.s3.bucket-name=bucket-exp1-s2
aws.region=${AWS_REGION:us-east-1}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.stack.auto=false

# =============================================
# SEMANA 4: Azure AD B2C - Validación JWT
# =============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://plataformaeducativa.b2clogin.com/tfp/e11fc11d-6421-48ad-86f5-ebefd1a94cc5/b2c_1_registro_login/v2.0/

spring.main.allow-bean-definition-overriding=true
spring.h2.console.settings.web-allow-others=true