# =============================================
# CONFIGURACIÓN H2 (base de datos en memoria)
# =============================================
spring.datasource.url=jdbc:h2:mem:plataforma_educativa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicialización de datos
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Puerto
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info

# =============================================
# CONFIGURACIÓN AWS S3
# =============================================
aws.s3.bucket-name=bucket-exp1-s2
aws.region=${AWS_REGION:us-east-1}

# Deshabilitar autoconfiguración de Spring Cloud AWS
# (tu proyecto usa SDK v2 directo en StorageConfig.java)
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.stack.auto=false

# SEMANA 4: Azure AD B2C - Validación JWT
# TU_DIRECTORY_ID = Directory (tenant) ID de tu app en Azure
# Encuéntralo en: App registrations > Tu app > Overview
spring.security.oauth2.resourceserver.jwt.issuer-uri=\
  https://login.microsoftonline.com/TU_DIRECTORY_ID/v2.0